### PR TITLE
Add zoom level asterisk, erase cached data feedback and fix symlink bug

### PR DESCRIPTION
**Pull request by shred86**
The following changes are made with this pull request:

**Features:**
- Added an asterisk next to the zoom level number for each tile in the Tiles and management window if custom zoom levels have been specified for a tile (screenshot below). This allows a user to quickly see which tiles have custom zoom levels without having to open the Preview / Custom zoomlevels window for each tile to check. In the example screenshot below, two tiles have been built and the bottom tile has custom zoom levels specified.
- Add console feedback when using "Erase cached data" options. Slightly redundant for the "Tile (whole)" option since the tile outline disappears but I added it for consistency when the other options are used since you get no feedback with those.

**Bug Fixes:**
- If one-click symlink feature is used, added removal of symlink when "Erase cached data" "Tile (whole)" option is used. Previously, this would broken symlinks. As a part of this, refactored the code and created two new methods `add_symlink` and `remove_symlink` in the `Ortho4XP_Earth_Preview` class.
- Fixed [typo](https://github.com/shred86/Ortho4XP/blob/939f1ce8d4a0fb8f3c07b5f64baa687b300887c9/src/O4_GUI_Utils.py#L1597) in variable naming.

zoom-level-asterik

@w8sl I think I saw you mention on the official repo that the progressive_zl branch had some similar feature. I'd be curious to get your feedback if this is something similar.

### CODE REVIEW

**Comment by w8sl** [comment]
Nice feature! No it this one was not present in progressive_zl. I have 2 versions of working Progressive_zl on my fork. It is relatively easy to do PyInstaller mod on 1.40, but it wants resource_path even in "Ortho4XP.py" which your fork doesn´t. I have it working at home.

**Comment by w8sl** [comment]
I have uploaded it to my dev branch. Not extensively tested yet.

**Comment by shred86** [comment]
Interestingly, this feature highlighted a strange bug I can't seem to replicate. I noticed a handful of my tiles was indicating it had custom zones but I never setup any for that tile. Checking the tile config, I can see a long list of entries for `zone_list` that were in a completely different area and the coordinates for that tile didn't have any custom zones. These were tiles that were built with the original version of Ortho4XP, so I'm pretty confident it's nothing that was introduced with any changes I've made. Even after deleting the tile and recreating it, the same `zone_list` would show up. I tried it on a clean install and it was not happening, so it's like something was cached that was causing issues. I ended up resolving it by deleting the tile of the coordinates of `zone_list` and the problematic tile, rebuilt them and now it's empty as I would expect.

Very strange but something I'll be keeping an eye on to see if I can replicate it so we can fix it.

**Comment by shred86** [comment]
Found a small issue with symlinks when you use the "Tiles (whole)" delete option, so I went ahead and fixed it as well as another small typo I found. Updated the original title and post. I want to keep PRs focused on one thing at a time to make it easier to review so I'm already breaking my own rule.

**Pull request merged**
